// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlayListsOfPlace(arg1) {
  return window['go']['playlist']['Playlist']['GetPlayListsOfPlace'](arg1);
}

export function Startup(arg1) {
  return window['go']['playlist']['Playlist']['Startup'](arg1);
}
