// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {playlist} from '../models';
import {context} from '../models';

export function GetPlayListsOfPlace(arg1:string):Promise<Array<playlist.PlaylistDTO>>;

export function Startup(arg1:context.Context):Promise<void>;
