// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateLibrary(arg1) {
  return window['go']['multimedia']['Library']['CreateLibrary'](arg1);
}

export function GetSong(arg1) {
  return window['go']['multimedia']['Library']['GetSong'](arg1);
}

export function ListLibraries() {
  return window['go']['multimedia']['Library']['ListLibraries']();
}

export function ListLibrary(arg1, arg2) {
  return window['go']['multimedia']['Library']['ListLibrary'](arg1, arg2);
}

export function ListLibraryContents(arg1, arg2) {
  return window['go']['multimedia']['Library']['ListLibraryContents'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['multimedia']['Library']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['multimedia']['Library']['OpenFolderDialog']();
}

export function Startup(arg1) {
  return window['go']['multimedia']['Library']['Startup'](arg1);
}
