// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateLibrary(arg1) {
  return window['go']['multimedia']['Library']['CreateLibrary'](arg1);
}

export function GetSong(arg1) {
  return window['go']['multimedia']['Library']['GetSong'](arg1);
}

export function GetSongAsync(arg1, arg2) {
  return window['go']['multimedia']['Library']['GetSongAsync'](arg1, arg2);
}

export function ListLibraries() {
  return window['go']['multimedia']['Library']['ListLibraries']();
}

export function ListLibraryContents(arg1, arg2) {
  return window['go']['multimedia']['Library']['ListLibraryContents'](arg1, arg2);
}

export function LoadLibraries() {
  return window['go']['multimedia']['Library']['LoadLibraries']();
}

export function OpenFileDialog() {
  return window['go']['multimedia']['Library']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['multimedia']['Library']['OpenFolderDialog']();
}

export function RemoveLibrary(arg1) {
  return window['go']['multimedia']['Library']['RemoveLibrary'](arg1);
}

export function SaveLibraries() {
  return window['go']['multimedia']['Library']['SaveLibraries']();
}

export function Startup(arg1) {
  return window['go']['multimedia']['Library']['Startup'](arg1);
}

export function UpdateLibraryName(arg1, arg2) {
  return window['go']['multimedia']['Library']['UpdateLibraryName'](arg1, arg2);
}

export function UpdateSearchIndex(arg1) {
  return window['go']['multimedia']['Library']['UpdateSearchIndex'](arg1);
}
