// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {multimedia} from '../models';
import {context} from '../models';

export function CreateLibrary(arg1:multimedia.Lib):Promise<void>;

export function GetSong(arg1:string):Promise<string>;

export function GetSongAsync(arg1:string,arg2:any):Promise<void>;

export function ListLibraries():Promise<Array<multimedia.Lib>>;

export function ListLibraryContents(arg1:string,arg2:string):Promise<Array<multimedia.LibItem>>;

export function LoadLibraries():Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function RemoveLibrary(arg1:string):Promise<void>;

export function SaveLibraries():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateLibraryName(arg1:string,arg2:string):Promise<void>;

export function UpdateSearchIndex(arg1:multimedia.LibItem):Promise<void>;
