// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Insert(arg1, arg2) {
  return window['go']['multimedia']['TrieNode']['Insert'](arg1, arg2);
}

export function ListAllContents() {
  return window['go']['multimedia']['TrieNode']['ListAllContents']();
}

export function Search(arg1) {
  return window['go']['multimedia']['TrieNode']['Search'](arg1);
}

export function Startup(arg1) {
  return window['go']['multimedia']['TrieNode']['Startup'](arg1);
}

export function TestSearch(arg1) {
  return window['go']['multimedia']['TrieNode']['TestSearch'](arg1);
}
