// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {multimedia} from '../models';
import {context} from '../models';

export function Insert(arg1:string,arg2:multimedia.LibItem):Promise<void>;

export function ListAllContents():Promise<Array<multimedia.LibItem>>;

export function Search(arg1:string):Promise<Array<multimedia.LibItem>>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestSearch(arg1:string):Promise<void>;
