// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNearbyPlaces(arg1, arg2) {
  return window['go']['place']['Place']['GetNearbyPlaces'](arg1, arg2);
}

export function GetPlaces() {
  return window['go']['place']['Place']['GetPlaces']();
}

export function Startup(arg1) {
  return window['go']['place']['Place']['Startup'](arg1);
}
